from django import forms
from alpha.events import models
import sha
import random

def get_event_form():
    class _EventForm(forms.ModelForm):
        class Meta:
            model = models.Event
            exclude = ('authentication_key',) # generated by view
    return _EventForm


def create_authentication_key(email):
    salt = sha.new(str(random.random())).hexdigest()[:5]
    return sha.new(salt+email).hexdigest()
